version: '2'
services:
  elektra:
    image: sapcc/elektra
    ports:
      - "5000:80"
    environment:
      POSTGRES_SERVICE_HOST: postgres
    links: [postgres]
    command: [script/wait-for-postgres.sh, script/start.sh]
     
  postgres:
    image: postgres:9.6

    
