<%
  options  = " --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'}" 
  options += " --format CI::Reporter::Cucumber --out #{ENV['CI_REPORTS'] || 'features/reports'}" if ENV['HEADLESS']
  options += " -r features"
  options += " CCTEST_DOMAIN=#{ENV['CCTEST_DOMAIN'] || 'cc3test'}"
  options += " CCTEST_PROJECT=#{ENV['CCTEST_PROJECT'] || 'member'}"
  options += " CCTEST_USER=#{ENV['CCTEST_USER'] || 'test_member'}"
  options += " CCTEST_PASSWORD=#{ENV['CCTEST_PASSWORD']}"
%>

default:     <%= options %> --strict --tags ~@wip --tags ~@admin features
acceptance:  <%= options %> --strict --tags ~@wip features/acceptance
smoke:       <%= options %> --strict --tags ~@wip --tags @javascript features/smoke
integration: <%= options %> --strict --tags ~@wip --tags @javascript features/integration
e2e:         <%= options %> --strict --tags ~@wip --tags ~@member --tags ~@admin --tags @javascript features/e2e
member:      <%= options %> --strict --tags ~@wip --tags @member features
admin:       <%= options %> --strict --tags ~@wip --tags @admin features