self_registration_domains:
  - monsoon2
  - monsoon3

credentials:
  types:
    - ec2
    - ssh-key

  blobs:
    ec2:
      - access
      - secret
    ssh-key:
      - name
      - public_key

# If you add a new version to the tou, create a new version key,
# set the ACTUAL_TERMS anchor to the new key and
# set the actual_terms_version to the new key
terms:
  actual_terms_version: &ACTUAL_TERMS_VERSION v2
  v2: &ACTUAL_TERMS >
    ### Overview

    #### Service Description

    IT Infrastructure Services will give the ability to provide standalone virtual operating systems as well as,
    software automation (Iaas +PaaS). This is the automated provisioning of virtual servers via a self-service using IT IS’s Converged Cloud Platform.
    These instances can be based on fixed sizes or customized specifically to the needs of the customers.

    #### Usage Guidelines

    Converged Cloud is intended for the use of Employees of SAP SE along with all subsidiaries.
    The end user is solely responsible for all content, development and use of content.
    You may use Converged Cloud to store, retrieve, query, serve and execute your content.
    Your content must follow SAP’s Acceptable Use Policy, the Converged Cloud teams reserves the right to remove any content that falls outside this policy.
    The end user is responsible for maintaining all installed software licenses that are not centrally provided by the Converged Cloud Service.

    #### Definitions

    In this document the terms "provider" and "platform" are used to represent the Converged Cloud platform and provided services.
    The term "user" is used to represent the SAP employees and contractors (inclusing technical user accounts) using the SAP Converged Cloud platform.

    ### Disclaimers

    #### Litigation Hold

    As content is decommissioned from Converged Cloud it the end user must note if any relevant content is subject to Litigation Hold.
    Litigation Hold Reminder identifies the materials that must continue to be preserved.
    As noted in that Litigation Hold Reminder, “this obligation shall continue for as long as the Lawsuit and any related appeals
    are ongoing and for as long thereafter as our counsel advises is appropriate.” Therefore, please continue to comply with
    the directive described in the corporate portal.

    #### Confidential Information

    The SAP Converged Cloud Team will use all reasonable efforts to preserve and protect any stored confidential data within the platform.
    Converged Cloud team is working with IT Security and Data Privacy to ensure CI.
    SAP will ensure that all employees and agents that have access to the data are legally bound not to disclose this information.
    Confidential Information shall mean all trade secrets and other information or Services which SAP or third parties protect
    against unrestricted disclosure to others which is labeled Confidential.

    #### Global Conditions

    Converged Cloud Infrastructure is provided in multiple global locations. The user has the authorization to select a location
    based on their specific needs. Once the system is located in a specific region the data privacy, CI, and legal terms
    follow the laws of that residing company. End users should be aware of this when determining a specific location for deployment.

    ### Terms

    #### Fees

    Converged Cloud systems are subject to reoccurring fees agreed upon requesting resource quotas for specific services.
    These fees are transparently updated and accessible to the user and the user's designated cost object will be used
    for charging these fees for the duration of quota allocation. It is the user's responsibility to maintain a correct
    cost object per organization. If the cost object is not valid we have to bill the personal Cost Center.
    SAP reserves the right to reasonably adjust fees based on current conditions.
    SAP will provide timely notice on any planned adjustments.

    #### Cookbooks

    Cookbooks are created and maintained by Open Community Standards. Cookbook owner is responsible for the maintenance and
    support of cookbooks. The platform team does not provide cookbook support.

    #### Security Zones

    The platform provides the capability to expose systems to different Network Zones: Internal Prod Biz, Internal and External.
    The user is required to create and maintain applicable Securiity Concepts according to the policies established within SAP.
    The submission and approval of the security concept is the responsibility of the user.
    
    #### Software Upgrades

    From time to time, the platform team may apply upgrades, patches, bug fixes or other maintenance to the Service Offerings,
    Operating Systems or Software. We agree to use reasonable efforts to avoid disruption during such maintenance. The plaform will
    inform users of any scheduled Maintenance which may result in Service disruption, except for emergency maintenance and users agree
    to use reasonable efforts to comply with any maintenance announced timely and/or without undue delay.

    ### User Obligations

    #### Platform Services

    Users must comply with current technical documentation applicable to the Services (including applicable developer guides) 
    as published on the platform documentation site.

    #### Network Configuration

    The user is responsible for the network configuration within his projects. This includes but is not limited to the exposure of
    services, the maintenance of internal Security Groups and the integrity and confidentiality of network traffic.

    #### Operating System Access and Responsibility

    The user is responsible to setup and operate the operating systems provisioned on the platform.
    The platform may provide the users operating system images which can be used to deploy system, this does not limit the
    responsibilities of the user to configure, operate and maintain the instances according to SAP Security Policies and Procedures.
    Users are encouraged to create, maintain and use custom images to fulfill regulatory, corporate, legal and contractual requirements.
    Administrative access to OS should not be granted to external parties. The platform team cannot guarantee to resolve any OS issue.
    Converged Cloud team will fully support all infrastructure issues, the platform APIs and orchestration layers.

    #### Access Control

    The user is responsible to oversee user access and role based access control within their respective platform projects. 

    #### Software Approval

    In case software is not available either via Converged Cloud Standard OS or Recipe you may have to order it via SRM.
    Note that all software installed on SAP hardware has to be “SWAP” approved.
    That means that the software has to pass the Software Approval Process and has to be rated white or grey in the
    SWAP Catalog before it can be ordered via SRM.

    #### Security Patching

    It is the user responsibility to ensure installation of any OS / Security patches that are requested by SAP Guidelines 
    and to comply with their guidance / requests and timelines.

    #### Change Management

    Any request for a system change within the user area of responsibility must follow applicable Change Management processes.
    Please note that certain Change Management processes can incur additional effort.

    #### Data processing

    Users must ensure applicable confidentiality of any data stored and processed within their area of responsibility,
    this includes but is not limited to access credentials, cryptographic secrets and enforcing applicable server-side encryption 
    of data.
    Users processing personal data of End Users or other identifiable individuals in their use of a Service are responsible for 
    providing legally adequate privacy notices and obtaining necessary consents for the processing of such data. Users ensure 
    that they provided all necessary privacy notices and obtained all necessary consents. Users are responsible for processing such 
    data in accordance with SAP policies and applicable law.

    #### Backup

    Converged Cloud offers the standard File system (FS) and DB Backup / Restore from the Global Backup Team.
    Users are responsible for requesting to enable backups on their systems. Backups are not enabled by default.
    The user is required to ensure that business critical data is properly protected against dataloss caused by infrastructure failure.

    #### High Avaiability and Disaster Recovery

    The platform provides means to increase the resilience of the users workload through documented measures for the implementation of 
    high availability (HA). The platform does not provide inherent high availability for the user application. 
    Disaster Revovery (DR) can be implemented by the user and shall be established according to their respective need to recover from
    infrastructure outages.

    ### LIMITATION OF LIABILITY

    TO THE EXTENT ALLOWABLE BY APPLICABLE LAW, SAP AND ITS AFFILIATES, SUBSIDIARIES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS,
    AND LICENSORS ARE NOT LIABLE TO ANY USER FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, CONSEQUENTIAL,
    OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, REVENUE, GOODWILL, USE, DATA, OR
    OTHER INTANGIBLE LOSSES (EVEN IF SAP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), HOWEVER CAUSED, WHETHER IN
    CONTRACT, TORT, OR OTHERWISE, ARISING OUT OF OR RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SAP.com, SAP SOFTWARE,
    OR SERVICES; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES ARISING OUT OF YOUR USE OR INABILITY TO USE
    ANY SAP SOFTWARE, CONTENT, OR SERVICES PURCHASED OR OBTAINED DURING TRANSACTIONS CONDUCTED ON THE SAP.com;
    (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA;
    (iv) STATEMENTS, MESSAGES, OR CONDUCT OF ANY THIRD PARTY ON THE SAP.com; OR
    (v) ANY OTHER MATTER RELATING TO THE SAP.com OR SERVICES. NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN,
    THESE LIMITATIONS SHALL NOT APPLY IN CASE OF INTENT OR GROSS NEGLIGENCE BY SAP AND IN CASE OF SAPS STATUTORY
    LIABILITY FOR PERSONAL INJURY AND DEFECTIVE PRODUCTS.

actual_terms:
  version: *ACTUAL_TERMS_VERSION
  terms: *ACTUAL_TERMS
